name: navysync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  go_router: ^14.8.1
  firebase_core: ^3.13.0
  flutter_riverpod: ^2.6.1
  intl: 0.20.2
  syncfusion_flutter_calendar: ^30.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
