// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAHpC9dlqn7MN71a1FbNQsZbvG_JwK5Uw',
    appId: '1:582606526370:web:5f7c1fd461b944fcc284fb',
    messagingSenderId: '582606526370',
    projectId: 'navysync-a8d94',
    authDomain: 'navysync-a8d94.firebaseapp.com',
    storageBucket: 'navysync-a8d94.firebasestorage.app',
    measurementId: 'G-KHB35PMZFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACarPM_witf4AFBG_3u3dthlN2i5mn-HA',
    appId: '1:582606526370:android:4d76511c6f04714ec284fb',
    messagingSenderId: '582606526370',
    projectId: 'navysync-a8d94',
    storageBucket: 'navysync-a8d94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6WHD52LPJYcBkpzAragpw1nEJpKJTzPs',
    appId: '1:582606526370:ios:a296d41a0bd9eb8cc284fb',
    messagingSenderId: '582606526370',
    projectId: 'navysync-a8d94',
    storageBucket: 'navysync-a8d94.firebasestorage.app',
    iosBundleId: 'com.example.navysync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6WHD52LPJYcBkpzAragpw1nEJpKJTzPs',
    appId: '1:582606526370:ios:a296d41a0bd9eb8cc284fb',
    messagingSenderId: '582606526370',
    projectId: 'navysync-a8d94',
    storageBucket: 'navysync-a8d94.firebasestorage.app',
    iosBundleId: 'com.example.navysync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAHpC9dlqn7MN71a1FbNQsZbvG_JwK5Uw',
    appId: '1:582606526370:web:2035427fb5849c0bc284fb',
    messagingSenderId: '582606526370',
    projectId: 'navysync-a8d94',
    authDomain: 'navysync-a8d94.firebaseapp.com',
    storageBucket: 'navysync-a8d94.firebasestorage.app',
    measurementId: 'G-19C4SGZTPE',
  );
}
